---
name: build-push ansible

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  workflow_dispatch:

env:
  OWNER: opslabhq
  FILE: ansible

permissions:
  contents: read

jobs:
  build-push-ansible:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4.2.0
        with:
          show-progress: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd ${FILE}

          echo "OWNER=${OWNER,,}" >> $GITHUB_ENV
          echo "OWNER=${OWNER,,}"

          echo "FILE=${FILE,,}" >> $GITHUB_ENV
          echo "FILE=${FILE,,}"

          BASE_VERSION=$(grep -oP '^ARG BASE_VERSION=\K.*' Dockerfile)
          echo "BASE_VERSION=${BASE_VERSION,,#v}" >> $GITHUB_ENV
          echo "BASE_VERSION=${BASE_VERSION,,#v}"

          TAG=$(grep -oP "^ARG IMAGE_VERSION=\K.*" Dockerfile)
          echo "TAG=${TAG,,#v}" >> $GITHUB_ENV
          echo "TAG=${TAG,,#v}"

          cd ..

      - name: Push
        uses: docker/bake-action@v5
        with:
          targets: push
          workdir: ./ansible

      - name: Push Rootless
        uses: docker/bake-action@v5
        with:
          targets: push-rootless
          workdir: ./ansible
