---
name: build-push ci-terraform

on:
  push:
    branches:
      - main
    paths:
      - 'ci/terraform/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  OWNER: opslabhq
  GROUP: ci
  FILE: terraform

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_ECR_PUBLIC }}
          role-session-name: "GitHubActions-${{ github.event.repository.owner.login }}-${{ github.event.repository.name }}-${{ github.run_id }}"
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2
        with:
          registry-type: public

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          BASE_VERSION=$(sed -n 's/^ARG BASE_VERSION=v\?\([0-9.]*\).*/\1/p' ./ci/terraform/Dockerfile)
          echo "BASE_VERSION=${BASE_VERSION#v}" >> $GITHUB_ENV
          echo "BASE_VERSION=${BASE_VERSION#v}"

          TAG=$(sed -n 's/^ARG IMAGE_VERSION=v\?\([0-9.]*\).*/\1/p' ./ci/terraform/Dockerfile)
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "TAG=${TAG#v}"

      - name: Push
        uses: docker/bake-action@2e3d19baedb14545e5d41222653874f25d5b4dfb # v5
        with:
          targets: push
          workdir: ./ci/terraform

      - name: Push Rootless
        uses: docker/bake-action@2e3d19baedb14545e5d41222653874f25d5b4dfb # v5
        with:
          targets: push-rootless
          workdir: ./ci/terraform
