---
name: build-push ansible

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  workflow_dispatch:

env:
  OWNER: opslabhq
  FILE: ansible

permissions:
  contents: read

jobs:
  build-push-ansible:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          show-progress: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd ${FILE}

          echo "OWNER=${OWNER,,}" >> $GITHUB_ENV
          echo "OWNER=${OWNER,,}"

          echo "FILE=${FILE,,}" >> $GITHUB_ENV
          echo "FILE=${FILE,,}"

          BASE_VERSION=$(sed -n 's/^ARG BASE_VERSION=\([0-9.]*\).*/\1/p' Dockerfile)
          echo "BASE_VERSION=${BASE_VERSION#v}" >> $GITHUB_ENV
          echo "BASE_VERSION=${BASE_VERSION#v}"

          TAG=$(sed -n 's/^ARG IMAGE_VERSION=\([0-9.]*\).*/\1/p' Dockerfile)
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "TAG=${TAG#v}"

          cd ..

      - name: Push
        uses: docker/bake-action@e626c7390c9f95508a135a89e65ec698e061fb2a # v5
        with:
          targets: push
          workdir: ./ansible

      - name: Push Rootless
        uses: docker/bake-action@e626c7390c9f95508a135a89e65ec698e061fb2a # v5
        with:
          targets: push-rootless
          workdir: ./ansible
