---
name: Build and Push Docker Image for alpine

on:
  push:
    branches:
      - main
    paths:
      - 'alpine/**'
  workflow_dispatch:

jobs:
  docker-build-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub Container Registry
        uses: docker/login-action@v3
        with:
          username: opslabhq
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          cd alpine

          ALPINE_VERSION=$(grep -oP '^ARG ALPINE_VERSION=\K.*' Dockerfile)
          echo "ALPINE_VERSION=${ALPINE_VERSION}" >> $GITHUB_ENV
          echo "ALPINE_VERSION=${ALPINE_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: alpine
          file: alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            opslabhq/alpine:${{ env.ALPINE_VERSION }}
            opslabhq/alpine:latest
